# ==============================================================================
# Word List 03
# ==============================================================================
suffer:
  title: suffer
  text: __suffer__ [ˈsʌfə(r)] v. 遭受，忍受；忍耐；容许；患病；受损失
impede:
  title: impede
  text: __impede__ [ɪmˈpiːd] vt. 阻碍，妨碍
spring:
  title: spring
  text: "__spring__ [sprɪŋ] n. 春天，春季；弹簧，发条；弹性，弹力；（源）泉；跳跃  \n\n__spring__ v. 跳跃；涌现，突然出现；突然提出（或说出）\n"
deduce:
  title: deduce
  text: __deduce__ [dɪˈdjuːs] v. 演绎，推断
doctorate:
  title: doctorate
  text: __doctorate__ ['dɒktərɪt] n. 博士学位
theoretical:
  title: theoretical
  text: __theoretical__ [ˏθɪəˈretɪkl] a. 理论（上）的
internship:
  title: internship
  text: __internship__ ['ɪntɜːnʃɪp] n. 实习身份；实习医师
slender:
  title: slender
  text: __slender__ [ˈslendə(r)] a. 修长的，细长的，苗条的；微小的，微薄的
respondent:
  title: respondent
  text: __respondent__ [rɪˈspɔndənt] n. 回答者，响应者；调查对象；被告
voluntary:
  title: voluntary
  text: __voluntary__ [ˈvɔləntrɪ] a. 自愿的，志愿的
submarine:
  title: submarine
  text: "__submarine__ [ˏsʌbməˈriːn; ˈsʌbməriːn] n. 潜水艇  \n\n__submarine__ a. 水底的，海底的\n"
notion:
  title: notion
  text: __notion__ [ˈnəuʃn] n. 概念，观念；想法
lavatory:
  title: lavatory
  text: __lavatory__ [ˈlævətrɪ] n. 盥洗室，厕所
tablet:
  title: tablet
  text: __tablet__ [ˈtæblɪt] n. 药片
fold:
  title: fold
  text: "__fold__ [fəuld] v. 折叠  \n\n__fold__ n. 皱；折\n"
compulsory:
  title: compulsory
  text: __compulsory__ [kəmˈpʌlsərɪ] a. 义务的；必须做的；强制性的；（课程）必修的
irritation:
  title: irritation
  text: __irritation__ [‚ɪrɪ'teɪʃn] n. 激怒，恼怒；刺激物，恼人的事
expense:
  title: expense
  text: __expense__ [ɪkˈspens] n. 花费，开支；消费，消耗；代价，损失
muddle:
  title: muddle
  text: "__muddle__ [ˈmʌdl] n. 一团糟，凌乱，混乱；（头脑）糊涂，困惑  \n\n__muddle__ vt. 将……弄成一团糟；使困惑，使糊涂；混淆\n"
originate:
  title: originate
  text: __originate__ [əˈrɪdʒɪneɪt] v. 起源，发生；首创，创造
induce:
  title: induce
  text: __induce__ [ɪnˈdjuːs] vt. 引诱，劝使；引起，导致；感应
disharmony:
  title: disharmony
  text: __disharmony__ [dɪsˈhɑːmənɪ] n. 不一致；不和谐
cosset:
  title: cosset
  text: "__cosset__ [ˈkɔsɪt] vt. 宠爱，溺爱 \n\n__cosset__ n. 宠儿\n"
crossword:
  title: crossword
  text: __crossword__ [ˈkrɔswɜːd] n. 纵横填字游戏
atomic:
  title: atomic
  text: __atomic__ [əˈtɔmɪk] a. 原子（能）的
disagree:
  title: disagree
  text: __disagree__ [ˏdɪsəˈgriː] v. 不同意；不一致
check-up:
  title: check-up
  text: __check-up__ ['tʃekʌp] n. 检查
silt:
  title: silt
  text: "__silt__ [sɪlt] n. 淤泥  \n\n__silt__ v. （用淤泥）阻塞\n"
inclusive:
  title: inclusive
  text: __inclusive__ [ɪnˈkluːsɪv] a. 包括一切费用在内的；所有数目（或首尾日期）包括在内的；包容广阔的
reservation:
  title: reservation
  text: __reservation__ [ˏrezəˈveɪʃn] n. 保留意见，存疑；预定，预订
transcript:
  title: transcript
  text: __transcript__ ['trænskrɪpt] n. 抄本，副本；文字记录
include:
  title: include
  text: __include__ [ɪnˈkluːd] v. 包括，包含；计入
abode:
  title: abode
  text: __abode__ [əˈbəud] n. 房屋，家，住所
gadget:
  title: gadget
  text: __gadget__ [ˈgædʒɪt] n. 小巧的器械，精巧的装置；小玩意
legacy:
  title: legacy
  text: __legacy__ [ˈlegəsɪ] n. 遗产，遗赠
leisure:
  title: leisure
  text: __leisure__ [ˈleʒə(r)] n. 空闲时间；悠闲
overlap:
  title: overlap
  text: __overlap__ [ˏəuvəˈlæp] v. （使）部分重叠，交叠
counterpart:
  title: counterpart
  text: __counterpart__ [ˈkauntəpɑːt] n. 与对方地位相当的人；配对物；副本
tune:
  title: tune
  text: "__tune__ [tjuːn] vt. 调音；调节，调整  \n\n__tune__ n. 调子；和谐\n"
strike:
  title: strike
  text: "__strike__ [straɪk] v. 打；折磨  \n\n__strike__ n. 罢工\n"
ambiguous:
  title: ambiguous
  text: __ambiguous__ [æmˈbɪgjuəs] a. 含糊其辞的； 不明确的，模棱两可的
vanish:
  title: vanish
  text: __vanish__ [ˈvænɪʃ] vi. 突然消失； 不复存在，消逝
mechanism:
  title: mechanism
  text: __mechanism__ [ˈmekənɪzəm] n. 机械装置；机制，机理；办法
dispute:
  title: dispute
  text: "__dispute__ [dɪˈspjuːt] n. 争论，争端，争吵  \n\n__dispute__ v. 对……表示异议；争论，争吵\n"
strengthen:
  title: strengthen
  text: __strengthen__ ['strŋθn] vt. 加强，巩固
workaholic:
  title: workaholic
  text: __workaholic__ [ˏwɜːkəˈhɔlɪk] n. 工作狂
unaware:
  title: unaware
  text: __unaware__ [ˏʌnəˈweə(r)] a. 未意识到的
erosion:
  title: erosion
  text: __erosion__ [ɪ'rəʊʒn] n. 腐蚀；磨损
exclusively:
  title: exclusively
  text: __exclusively__ [ɪk'skluːsɪvlɪ] ad. 专有地，专门地
feather:
  title: feather
  text: __feather__ [ˈfeðə(r)] n. 羽毛，翎毛
pronounceable:
  title: pronounceable
  text: __pronounceable__ [prə'naʊnsəbl] a. （指声音）发得出的；（指词）可发音的
bare:
  title: bare
  text: __bare__ [beə(r)] a. 赤裸的，光秃的
luggage:
  title: luggage
  text: __luggage__ [ˈlʌgɪdʒ] n. 行李
hose:
  title: hose
  text: "__hose__ [həuz] n. 软管  \n\n__hose__ vt. 用软管淋\n"
bulb:
  title: bulb
  text: __bulb__ [bʌlb] n. 灯泡
ion:
  title: ion
  text: __ion__ [ˈaɪən] n. 离子
cruise:
  title: cruise
  text: "__cruise__ [kruːz] v. 航游，巡航；（出租车、船等）缓慢巡行 \n\n__cruise__ n. 旅游，游戈\n"
shave:
  title: shave
  text: __shave__ [ʃeɪv] n./v. 修面
